// Copies of ohg.world's work gallery and the Brandex catalogue, resized to 1200px and
// served from public/gallery: this site ships images unoptimized.

export type GalleryImage = {
  src: string
  alt: string
  title: string
  caption: string
  width: number
  height: number
}

const ohg = (file: string, title: string, caption: string, width: number, height: number): GalleryImage => ({
  src: `/gallery/ohg/${file}.jpg`,
  alt: `${title} packaging, pre-press by OHG`,
  title,
  caption,
  width,
  height,
})

const brandex = (file: string, title: string, caption: string, width: number, height: number): GalleryImage => ({
  src: `/gallery/brandex/${file}.jpg`,
  alt: `${title}, from Brandex`,
  title,
  caption,
  width,
  height,
})

// Captions are ohg.world's own, from its work gallery.
export const ohgImages: GalleryImage[] = [
  ohg('pepsi', 'Pepsi — Stay Thirsty', 'Multi-market can programme, process build consolidated to spot', 1200, 675),
  ohg('baltika-7', 'Baltika 7', 'Europe edition series, fine line detail held across five designs', 1200, 1030),
  ohg('7up', '7UP', 'Standard and Zero variants, single palette across both', 1200, 744),
  ohg('boat-booze', 'Boat Booze', 'Four-flavour line, engraved illustration on a shared white base', 1200, 937),
  ohg('amstel-bier', 'Amstel Bier', 'Premium and malt variants across a single press fingerprint', 1200, 675),
  ohg('mountain-dew', 'Mountain Dew', 'High-chroma green held within tolerance across markets', 1200, 1200),
  ohg('amstel-sin', 'Amstel Sin', 'Alcohol-free line, metallic substrate read as a printing ink', 876, 1200),
  ohg('mighty-swell', 'Mighty Swell', 'Slim format sparkling cocktails, fine type at reduced diameter', 860, 1200),
  ohg('dr-pepper', 'Dr Pepper', 'Deep red base with embossed-effect detail', 800, 1200),
  ohg('kotsberg', 'Kotsberg', 'Strong beer line, gold and red held against a metal ground', 1080, 1200),
  ohg('celsius-dragonfruit', 'Celsius Dragonfruit Lime', 'Slim sleeve, white ground, fruit photography against bare metal', 675, 1200),
  ohg('fanta-grape', 'Fanta Grape', 'Deep violet base, high-chroma fruit over a saturated ground', 1200, 1200),
  ohg('kinza-cola', 'Kinza Cola', 'Slim can, deep blue ground with a metallic highlight', 960, 1200),
  ohg('monster-original', 'Monster Energy', 'Matte black sleeve, one high-chroma mark over a dark ground', 800, 1200),
  ohg('celsius-fuji-apple-pear', 'Celsius Fuji Apple Pear', 'Silver sleeve, fine type held at reduced diameter', 800, 1200),
  ohg('lipton-mango', 'Lipton Mango', 'PET bottle wrap, warm liquid read through the label', 960, 1200),
  ohg('sprite', 'Sprite', 'Green ground with fine white knockout and citrus detail', 800, 1200),
  ohg('fanta-pineapple', 'Fanta Pineapple', 'Saturated yellow, warm highlight over a dark ground', 1200, 1200),
  ohg('fanta-lychee', 'Fanta Lychee', 'Pink ground, pastel gradient carried across the wrap', 900, 1200),
  ohg('celsius-strawberry-kiwi', 'Celsius Strawberry Kiwi', 'Two variants sharing one white base', 961, 1200),
  ohg('kinza-diet-cola', 'Kinza Diet Cola', 'Silver sleeve, the metal read as a printing ink', 960, 1200),
  ohg('lipton-peach', 'Lipton Peach', 'Slim can, warm gradient with fine legal type', 960, 1200),
  ohg('kinza-citrus', 'Kinza Citrus', 'High-chroma lime green across a full wrap', 900, 1200),
  ohg('juice-monster', 'Juice Monster', 'Pink over black, single spot at full strength', 675, 1200),
  ohg('dr-pepper-strawberries-cream', 'Dr Pepper Strawberries & Cream', 'Standard and zero variants, one palette across both', 927, 1200),
  ohg('dr-pepper-creamy-coconut', 'Dr Pepper Creamy Coconut', 'Limited edition pair, pale ground with fine script', 960, 1200),
  ohg('monster-mango', 'Monster Energy Mango', 'Slim sleeve, high chroma over a cool ground', 771, 1200),
  ohg('7up-355', '7UP 355ml', '355ml format, green ground with white knockout', 848, 1200),
  ohg('pepsi-splash', 'Pepsi', 'Deep blue ground, metallic highlight around the mark', 966, 1200),
  ohg('fanta-orange-slim', 'Fanta Orange', 'Slim 250ml format, orange over a cool ground', 800, 1200),
  ohg('red-bull-winter', 'Red Bull Winter Edition', 'Seasonal variant, warm red over the silver base', 1014, 1200),
  ohg('coca-cola', 'Coca-Cola', 'Red ground, one spot colour at full strength', 911, 1200),
  ohg('7up-zero-pair', '7UP and 7UP Zero', 'Two variants, one green split across both', 1200, 1200),
  ohg('red-bull-classic', 'Red Bull', 'Silver and blue base, the metal participating in the colour', 960, 1200),
  ohg('red-bull-summer', 'Red Bull Summer Edition', 'Seasonal pink over the silver base', 1200, 1200),
  ohg('batiste-blush-cherry', 'Batiste — Blush and Cherry', 'Aerosol variants, pastel grounds held across the range', 960, 1200),
  ohg('batiste-dry-shampoo-range', 'Batiste — Dry Shampoo range', 'Six aerosol variants sharing one structural design', 1200, 1200),
  ohg('ben-jerrys-chewy-gooey', "Ben & Jerry's — Chewy Gooey Cookie", 'Deep-drawn ice cream tub, photographic inclusions on a saturated ground', 1200, 1200),
  ohg('ben-jerrys-vanilla-caramel-fudge', "Ben & Jerry's — Vanilla Caramel Fudge", 'Ice cream tub, hand-drawn detail held at reduced size', 1200, 1200),
  ohg('bimbo-oat-range', 'Bimbo — Oat range', 'Four flow-wrap variants sharing one structural system', 849, 1200),
  ohg('cadbury-dairy-milk-coffee-almond', 'Cadbury — Dairy Milk Coffee Almond', 'Foil and wrap, brand purple held across both', 675, 1200),
  ohg('cerave-moisturising-cream', 'CeraVe — Moisturising Cream', 'Jar and closure, clinical palette with no colour drift', 798, 1200),
  ohg('cerave-moisturising-range', 'CeraVe — Moisturising range', 'Tube and jar, one build across two forming processes', 900, 1200),
  ohg('cheetos', 'Cheetos', 'Metallised film bag, character line detail on a saturated ground', 1200, 1200),
  ohg('colgate-max-fresh', 'Colgate — MaxFresh', 'Laminate tube, gel imagery across the crimped end', 933, 1200),
  ohg('colgate-optic-white', 'Colgate — Optic White Pro Series', 'Laminate tube and carton, one colour across two substrates', 1200, 1200),
  ohg('davidoff-classic', 'Davidoff — Classic', 'Hinge-lid pack, warning and code areas registered to the lid seam', 937, 1200),
  ohg('davidoff-silver', 'Davidoff — Silver', 'Hinge-lid pack, metallised ground with colour verified on it', 937, 1200),
  ohg('doritos', 'Doritos', 'Metallised film bag, saturated ground over a reflective base', 960, 1200),
  ohg('dougs-cereal-carton', "Doug's — Chocolate cereal", 'Folding carton, tone curve rebuilt for an absorbent board', 1200, 1200),
  ohg('dove-advanced-care', 'Dove — Advanced Care', 'Monobloc aerosol, soft gradient held on a tapered body', 1200, 1200),
  ohg('dove-body-wash-range', 'Dove — Body wash range', 'Three variants, photographic fruit on a formed bottle', 960, 1200),
  ohg('dove-mousse-range', 'Dove — Body Love mousse', 'Three variants, one palette across a formed bottle', 1018, 1200),
  ohg('evian-pet', 'evian', 'PET bottle, colour specified against a transparent fill', 1171, 1200),
  ohg('haagen-dazs-coffee-chocolate', 'Häagen-Dazs — Coffee Chocolate', 'Ice cream tub, lid and wall registered as one artwork', 1200, 674),
  ohg('haagen-dazs-mango-raspberry', 'Häagen-Dazs — Mango & Raspberry', 'Ice cream tub, fruit imagery carried across the drawn wall', 1200, 1200),
  ohg('haagen-dazs-mango-raspberry-set', 'Häagen-Dazs — Mango & Raspberry, range shot', 'Tub programme, one palette across the flavour range', 960, 1200),
  ohg('kitkat', 'KitKat', 'Flow-wrap, foil ground under a four-colour build', 960, 1200),
  ohg('la-roche-posay-anthelios', 'La Roche-Posay — Anthelios UVMune 400', 'Bottle and closure, regulated claim areas locked before build', 805, 1200),
  ohg('la-roche-posay-serums', 'La Roche-Posay — Serum range', 'Four bottles, one system across differing fills', 960, 1200),
  ohg('la-roche-posay-toleriane', 'La Roche-Posay — Toleriane', 'Laminate tube, small legal type held across the crimp', 670, 1200),
  ohg('lays-chile-limon', "Lay's — Chile Limón", 'Film bag, market variant against the masterbrand palette', 960, 1200),
  ohg('lays-magic-masala', "Lay's — India's Magic Masala", 'Film bag, market variant on a shared masterbrand build', 848, 1200),
  ohg('lays-sizzlin-hot', "Lay's — Sizzlin' Hot", 'Film bag, saturated ground with photographic inclusions', 960, 1200),
  ohg('loreal-elvive-oil', "L'Oréal — Elvive Extraordinary Oil", 'PET bottle and pump, colour built against the product behind it', 800, 1200),
  ohg('marlboro-hinge-lid', 'Marlboro', 'Hinge-lid pack, print and emboss held in register', 960, 1200),
  ohg('mini-oreo-pouch', 'Mini Oreo', 'Stand-up pouch, photographic detail across a gusseted base', 800, 1200),
  ohg('nescafe-clasico-colombia', 'NESCAFÉ — Clásico Colombia', 'Glass jar, origin edition on the standing label system', 800, 1200),
  ohg('nescafe-classic', 'NESCAFÉ — Classic', 'Glass jar, label colour built against a dark fill', 800, 1200),
  ohg('nescafe-gold', 'NESCAFÉ — Gold', 'Glass jar, gold decoration registered to the closure', 800, 1200),
  ohg('nesquik-cereal-carton', 'Nesquik', 'Folding carton, character detail across creases and folds', 942, 1200),
  ohg('nivea-extra-bright', 'NIVEA — Extra Bright 10 Super', 'Laminate tube, fine legal type across a stretched wall', 800, 1200),
  ohg('nivea-rich-care-oil', 'NIVEA — Rich Care Shower Oil', 'Bottle and closure, gold read against a translucent fill', 741, 1200),
  ohg('nutella', 'Nutella', 'Glass jar, label and closure registered as one system', 960, 1200),
  ohg('pringles-cheese', 'Pringles — Cheese', 'Composite can, second variant on the same wrap system', 1200, 1200),
  ohg('pringles-paprika', 'Pringles — Paprika', 'Composite can, wrap-around label with a seam to hide', 1200, 1200),
  ohg('pringles-pop-the-energy', 'Pringles — Pop the Energy', 'Composite can, campaign variant on the standing wrap', 799, 1200),
  ohg('rexona-men', 'Rexona Men — MotionSense', 'Monobloc aerosol, gradient carried over the shoulder', 960, 1200),
  ohg('sanpellegrino-aranciata-rossa', 'Sanpellegrino — Aranciata Rossa', 'Slim can, dry offset over a metallised base', 801, 1200),
  ohg('twix', 'Twix', 'Flow-wrap, register held on a moving web', 960, 1200),
]

export const brandexImages: GalleryImage[] = [
  brandex('roasted-coffee-bag-packaging-design-ai-psd-editable-mockup', 'Roasted Coffee Bag Packaging Template – Cardamom Cream Pouch Design', 'Packaging template', 800, 1200),
  brandex('moto-chewing-gum-packaging-tin-box-vector-mockup-6-flavors', 'Chewing Gum Tin Box Packaging Template – Multi-Flavor Collection', 'Packaging template', 1200, 800),
  brandex('wine-bottle-label-mockup-eps-realistic-presentation', 'Premium Wine Bottle Label Packaging Template – Artistic Illustrated Collection', 'Packaging template', 1200, 800),
  brandex('reakoffs-gum-packaging-mockup-template-vector-ai-eps-editable', 'Reakoffs Gum Tin Packaging Mockup Template - Vector AI PSD Editable', 'Packaging template', 1200, 880),
  brandex('organic-instant-coffee-jar-product-mockup-rustic-plantation-scene', 'Instant Coffee Jar Label Template – Plantation Scene Mockup', 'Packaging template', 1200, 627),
  brandex('vibrant-tropical-fruit-candy-bar-wrapper-packaging', 'Brand Cherry Grape Lemon Candy Bar Packaging - Swirl Pattern Design', 'Packaging template', 1062, 1200),
  brandex('free-gum-tin-packaging-mockup-black-customizable-vector-art', 'Reakoffs Buzz All Night Gum Tin Packaging Mockup - Black Vector Art', 'Packaging template', 1200, 544),
  brandex('christmas-irish-drink-box-packaging-die-line-template-eps-vector', 'Christmas Smooth Irish Drink Bottle Label Template – Red Tree Design', 'Packaging template', 1200, 678),
  brandex('gourmet-pasta-packaging-mockup-with-chef-portrait-and-farfalle', 'Gourmet Pasta Packaging Mockup with Chef Portrait and Farfalle', 'Packaging template', 1200, 960),
  brandex('vintage-christmas-beverage-label-eps-template-holiday-drink-packaging', 'Vintage Christmas Liquor Bottle Label Packaging Template – Green & Gold', 'Packaging template', 1200, 678),
  brandex('reno-dath-beverage-bottle-labels-skeleton-character-photoshop', 'Reno Dath Beverage Bottle Labels Skeleton Character Photoshop', 'Packaging template', 800, 1200),
  brandex('eps-packaging-template-christmas-irish-cream-liqueur-drink-bottle', 'Christmas Smooth Irish Drink Bottle Label Template – Black & Red Wave Design', 'Packaging template', 1200, 678),
  brandex('whimsical-cow-theme-milk-carton-packaging-design-for-dairy-products', 'Milk Carton Packaging Mockup Set – Cow in Suit & Glasses Design', 'Packaging template', 1200, 1200),
  brandex('vibrant-coffee-cup-mockup-psd-with-dynamic-swirls-orange-background', 'Lidless Paper Coffee Cup Mockup Filled with Latte on Warm Beige Background', 'Mockup', 1200, 904),
  brandex('skincare-cream-jar-floating-mockup-green-background-branding', 'Skincare Cream Jar Floating Mockup Green Background Branding', 'Mockup', 1200, 1200),
  brandex('pink-frosted-glass-cosmetic-bottle-mockup-skincare-product', 'Pink Frosted Glass Cosmetic Bottle Mockup Skincare Product', 'Mockup', 800, 1200),
  brandex('realistic-aluminum-beverage-can-mockup-with-concrete-arch-background', 'Realistic Aluminum Beverage Can Mockup with Concrete Arch Background', 'Mockup', 1200, 848),
  brandex('outdoor-building-facade-wall-sign-mockup-realistic-branding', 'Outdoor Building Facade Wall Sign Mockup Realistic Branding', 'Mockup', 960, 1200),
  brandex('floating-magenta-coffee-cup-mockup-with-lid-on-teal-background', 'Floating Magenta Paper Coffee Cup Mockup with Purple Lid on Teal Background', 'Mockup', 826, 1200),
  brandex('sleek-floating-cosmetic-jar-mockup-white-lid-gradient-background', 'Sleek Floating Cosmetic Jar Mockup White Lid Gradient Background', 'Mockup', 1200, 903),
  brandex('realistic-handheld-snack-bar-packaging-mockup-beige-background', 'Realistic Handheld Snack Bar Packaging Mockup Beige Background', 'Mockup', 672, 1200),
  brandex('cosmetic-tube-mockup-minimalist-purple-background-product-display', 'Cosmetic Tube Mockup Minimalist Purple Background Product Display', 'Mockup', 904, 1200),
  brandex('metallic-red-pump-bottle-branding-mockup-handheld', 'Metallic Red Pump Bottle Branding Mockup Handheld', 'Mockup', 1200, 1200),
  brandex('dual-color-t-shirt-apparel-mockup-realistic-high-resolution-psd', 'Dual Color T-Shirt Apparel Mockup Realistic High-Resolution PSD', 'Mockup', 1200, 866),
  brandex('dark-green-matte-plastic-bag-mockup-with-handle-white-background', 'Dark Green Matte Plastic Bag Mockup with Handle White Background', 'Mockup', 1200, 1200),
]
